version: '3.8'

services:
  # ----------------------------------------
  devcontainer:
    build:
      context: ..
      dockerfile: Dockerfile.develop
    volumes:
      - ..:/workspace
    command: sleep infinity
  # ----------------------------------------
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  # ----------------------------------------

volumes:
  postgres-data: